base:
  maxp: 7
  UCT_maxiter: 1000
  UCT_extra_iter_for_point_pos: 1000

  CONSTRAINT_CROSS_EDGE: 1
  CONSTRAINT_BUCKLE: 0

  E: 1.93e+11
  pho: 8.0e+3
  sigma_T: 123.0e+6
  sigma_C: 123.0e+6
  slenderness_ratio_c: 180.0
  slenderness_ratio_t: 220.0
  dislimit: 0.002
  epoch: 10
  num_eval_steps_per_epoch: 1000
  batch_size: 200

  input_path: input/kr-sundial-newinput.txt

  save_path: output/results_3d/kr_sundial/
  input_path_2: output/PostResults/kr_sundial/
  save_model_path: output/saved_models/kr_sundial/
  MASS_OUTPUT_ALL_THRESHOLD: 300
  OUTPUT_ALL_THRESHOLD: 0
